 let productos =[
    {
        "id": 1,
        "name": "iPhone 12 Pro Max",
        "price": 410000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/celulares/iphone/Apple-iPhone-12-Pro-Max.png?raw=true",
        "freeShipping":true,
        "tradename":"iPhone",
        "category":"smartphones",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['iphone','iPhone','apple','smartphones','celular','celulares','ipone','phone','phones','smart','smartphone','iphone 12','iphone 12 pro max','pro','12','iphone 12 pro','max']
    },
    {
        "id": 2,
        "name": "iPhone 12",
        "price": 290000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/celulares/iphone/iphone12.png?raw=true",
        "freeShipping":true,
        "tradename":"iPhone",
        "category":"smartphones",
        "bestSeller": false,
        "stock": 1000,
        "tags": ['iphone','iPhone','apple','smartphones','celular','celulares','ipone','phone','phones','smart','smartphone','iphone 12','iphone 12 pro max','pro','12','iphone 12 pro','max']
    },
    {
        "id": 3,
        "name": "iPhone 13",
        "price": 300000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/celulares/iphone/iphone13.png?raw=true",
        "freeShipping":true,
        "tradename":"iPhone",
        "category":"smartphones",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['iphone','iPhone','apple','smartphones','celular','celulares','ipone','phone','phones','smart','smartphone','iphone 13','iphone 13 pro max','pro','13','iphone 13 pro','max']
    },
    {
        "id": 6,
        "name": "iPhone 13 Pro Max",
        "price": 380000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/celulares/iphone/iphone_13_pro_verde_03_ad_l.jpg?raw=true",
        "freeShipping":true,
        "tradename":"iPhone",
        "category":"smartphones",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['iphone','iPhone','apple','smartphones','celular','celulares','ipone','phone','phones','smart','smartphone','iphone 13','iphone 13 pro max','pro','13','iphone 13 pro','max']
    },
    {
        "id": 7,
        "name": "iPhone 11",
        "price": 188500,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/celulares/iphone/iphone_13_pro_verde_03_ad_l.jpg?raw=true",
        "freeShipping":true,
        "tradename":"iPhone",
        "category":"smartphones",
        "bestSeller": false,
        "stock": 1000,
        "tags": ['iphone','iPhone','apple','smartphones','celular','celulares','ipone','phone','phones','smart','smartphone','iphone 11','11','iphone 11 pro']
    },
    {
        "id": 20,
        "name": "iPhone 14",
        "price": 546000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/celulares/iphone/iphone14.jpg?raw=true",
        "freeShipping":true,
        "tradename":"iPhone",
        "category":"smartphones",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['iphone','iPhone','apple','smartphones','celular','celulares','ipone','phone','phones','smart','smartphone','iphone 14','14','iphone 14 pro max','iphone 14 pro','nuevo','nuevo iphone','iphone 2022','iphone 2023']
    },
    {
        "id": 8,
        "name": "Samsung SM-A505",
        "price": 54600,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/celulares/samsung/SM-A505_001_Front.png?raw=true",
        "freeShipping":true,
        "tradename": "Samsgung",
        "category":"smartphones",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['samsung','celular','smartphone','smartphones','samsun','galaxy','samsung galaxy','samsung a50','a50','samsung']
    },
    {
        "id": 19,
        "name": "Samsung Galaxy Z Flip4",
        "price": 215000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/celulares/samsung/samsungzflip.jpg?raw=true",
        "freeShipping":true,
        "tradename": "Samsgung",
        "category":"smartphones",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['samsung','celular','smartphone','smartphones','samsun','galaxy','samsung galaxy','samsung zflip','z flip 4','4','samsung zflip 4','zflip 4']
    },
    {
        "id": 9,
        "name": "iPad Air 4",
        "price": 109000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/tablets/iphone/Apple_iPad_Air_4.png?raw=true",
        "freeShipping":true,
        "tradename":"iPhone",
        "category":"tablets",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['iphone','iPhone','apple','ipad','iPad','tablet','tablets','ipad air 4','air 4','tablet ipad','tablet iphone']
    },
    {
        "id": 10,
        "name": "iPad Pro",
        "price": 204000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/tablets/iphone/Ipad-pro.png?raw=true",
        "freeShipping":true,
        "tradename":"iPhone",
        "category":"tablets",
        "bestSeller": false,
        "stock": 1000,
        "tags": ['iphone','iPhone','apple','ipad','iPad','tablet','tablets','ipad pro','iPad pro','tablet ipad pro','tablet iphone']
    },
    {
        "id": 11,
        "name": "Samsung Tab S6 Lite",
        "price": 75000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/tablets/samsung/samsung-tabS6lite.png?raw=true",
        "freeShipping":true,
        "tradename":"Samsung",
        "category":"tablets",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['samsung','tablet','tablets','samsung tablet','tab','samsung tab','s6','samsung s6','samsung s6 lite','lite','tablet samsung']
    },
    {
        "id": 12,
        "name": "AKG k420 Studio",
        "price": 40000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/headsets/AKG_k240_studio.png?raw=true",
        "freeShipping":true,
        "tradename":"AKG",
        "category":"headsets",
        "bestSeller": false,
        "stock": 1000,
        "tags": ['headsets','headset','auriculares','auris','headphones','head','auricular','akg','AKG','k420 studio','auricular akg','studio']
    },
    {
        "id": 13,
        "name": "Corsair Virtuoso Special Edition",
        "price": 45000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/headsets/corsair%20virtuoso%20special%20edition.png?raw=true",
        "freeShipping":true,
        "tradename":"Corsair",
        "category":"headsets",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['headsets','headset','auriculares','auris','headphones','head','auricular','virtuoso','corsair','special edition','Corsair']
    },
    {
        "id": 14,
        "name": "ASUS x509MA Intel n4020",
         "price": 131950,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/netbook/asus%20x509MA%20intel%20n4020.png?raw=true",
        "freeShipping":true,
        "tradename":"ASUS",
        "category": "netbooks",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['asus','ASUS','netbooks','notebooks','netbook','notebook','pc','escritorio','medio','gama media','netbook asus','notebook asus','netbooks asus','notebooks asus']
    },
    {
        "id": 15,
        "name": "Lenovo IP Gaming 3",
        "price": 131950,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/netbook/lenovo%20ip%20gaming%203.png?raw=true",
        "freeShipping":true,
        "tradename":"Lenovo",
        "category": "netbooks",
        "bestSeller": false,
        "stock": 1000,
        "tags": ['lenovo','netbooks','notebooks','netbook','notebook','notebook lenovo','netbook lenovo','pc']
    },   
    {
        "id": 16,
        "name": "Lenovo Thinkbook 15",
        "price": 147000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/netbook/lenovo%20thinkbook%2015.png?raw=true",
        "freeShipping":true,
        "tradename":"Lenovo",
        "category": "netbooks",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['lenovo','thinkbook','netbooks','notebooks','netbook','notebook','notebook lenovo','netbook lenovo','thinkbook 15','15','pc']
    },
    {
        "id": 17,
        "name": "Razer Blade 15",
        "price": 598000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/netbook/Razer-Blade-15.jpg?raw=true",
        "freeShipping":true,
        "tradename":"Razer",
        "category": "netbooks",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['netbook','razer','netbooks','notebook','notebooks','blade','razer blade 15','gamer','gamming','game','notebook gammer','netbook gammer','alta gama','pro','netbook pro']
    },
    {
        "id": 18,
        "name": "Dell Inspiron n5559",
        "price": 200000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/netbook/dell%20inspiron%20n5559.png?raw=true",
        "freeShipping":true,
        "tradename":"Dell",
        "category": "netbooks",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['dell','notebook','notebooks','netbooks','netbook','inspiron','dell inspiron','Dell','notebook dell','dell notebooks']
    },
    {
        "id": 21,
        "name": "MacBook Pro",
        "price": 653000,
        "image":"https://github.com/facundoiba95/eShopCBA-API/blob/master/netbook/macbookpro.jpg?raw=true",
        "freeShipping":true,
        "tradename":"MacBook",
        "category": "netbooks",
        "bestSeller": true,
        "stock": 1000,
        "tags": ['iphone','iPhone','apple','notebook','notebook','netbook','macbook','pro','macbook pro','macBook','macBook pro']
    }  
]

module.exports = productos;


